### ISSUE TITLE
tier 2 swag: [overview/design] order store products by tier

### ISSUE THREAD

**Issue by amberleyromo** [gatsbyjs/store.gatsbyjs.org#173]
Reorganize products in store to be grouped by what tier they belong to (in shopify admin "collections")

- Stickers are free with any order
- Tier 1:
  - T-shirts
  - Socks
  - Hats
- Tier 2:
  - Hoodies
  - Coffee tumblers (upcoming)
  - Pajama pants (upcoming)

## Todo
- [x] #179: Create the separation in Shopify (needs to be done by an Inkteam member)
- [x] #180: (this issue) Design a solution for making it visually apparent which items are available as part of which contributor tier
- [x] #181: Implement the new design in the UI

**Comment by jlengstorf** [comment]
This needs to be visually apparent in the store UI somehow. It could be done through filters, through subheading groupings, through badges on the products, or something else, but we need to make it obvious so there's no confusion about why one product gets the discount and another doesn't.

A stretch goal for this would be to have the badges be auth-aware, showing contributors what they can get for free with their currently unclaimed discount codes.

**Comment by jlengstorf** [comment]
So there are actually a couple tasks here, on thinking about this more:

1. Create the separation in Shopify (needs to be done by an Inkteam member)
2. Design a solution for making it visually apparent which items are available as part of which contributor tier
3. Implement the new design in the UI

We should probably split these into distinct issues to make them individually assignable.

**Comment by amberleyromo** [comment]
Closing this overview issue in favor of #204
