### ISSUE TITLE
tier 2 swag: [overview/design] accommodate tier 2 code in dashboard UI 

### ISSUE THREAD

**Issue by amberleyromo** [gatsbyjs/store.gatsbyjs.org#175]
Create design solution ~in `/account/dashboard`~ to show 1-2 discount codes (and potentially “used” discount codes).

- [x] #173: [design] order store products by tier
- [x] #176: [design] Handle used coupon codes for logged-in users
- [x] #117: [design] Product detail pages
- [x] #177: [design] enhance product preview
- [x] #180: [design] make connection between products and tier visually apparent

**Comment by jlengstorf** [comment]
This is going to have two phases: design and implementation. Can we split it out to make sure we don't try to design in code? Wireframing might be the best path forward on this to keep the iteration time low.

**Comment by amberleyromo** [comment]
@jlengstorf I turned this issue into the design issue, and created an implementation issue: #182

**Comment by amberleyromo** [comment]
Notes and considerations jumping off https://github.com/gatsbyjs/store.gatsbyjs.org/issues/175#issuecomment-438476784

- Add visual indicator that side panel can be minimized/opened.
- Add a floating design detailing that all orders over $10 get a free sticker pack
- Add filtering for products eligible for the different contributor tiers.
  - Filtering should be extensible for later use (sizes, types of swag, etc)
- Pre-fill [code claim/newsletter sign-up form)[https://user-images.githubusercontent.com/3461087/48449472-3533c380-e768-11e8-902a-2943451970a7.png] with user GitHub data, check newsletter box by default.
- Add a link to the size chart and care instructions on individual product pages.
- "Level 1" and "Level 2" instead of "Tier 1" and "Tier 2"
- Add hints for next swag level. (e.g., if a contributor is claiming level 1 swag, visually hint what swag is eligible for level 2, how many more contributions to claim, etc).
- Add link to store product thumbnails to "see details" (not just click thumbnail to see product detail page)
- Add to the store a link/CTA for people hosting meetups/events to request swag (airtable form: https://airtable.com/shrpwc99yogJm9sfI)

**Comment by jlengstorf** [comment]
One note: I think we might just drop the "No thank you" button next to the GitHub login in favor of a sidebar toggle.

Otherwise this all looks great. Thanks!
